# Generated by Django 5.2.6 on 2025-11-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooler',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cpu',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disco',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fuente',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gpu',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mouse',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notebook',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paquete_office',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pcescritorio',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placa_wifi',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ram',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sistema_operativo',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teclado',
            name='realidadAumentada',
            field=models.BooleanField(default=False),
        ),
    ]
