# Generated by Django 5.2.6 on 2025-11-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computacion', '0002_cooler_realidadaumentada_cpu_realidadaumentada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooler',
            name='realidadAumentada',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='realidadAumentada',
        ),
        migrations.RemoveField(
            model_name='disco',
            name='realidadAumentada',
        ),
        migrations.RemoveField(
            model_name='fuente',
            name='realidadAumentada',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='realidadAumentada',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='realidadAumentada',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='realidadAumentada',
        ),
        migrations.RemoveField(
            model_name='paquete_office',
            name='realidadAumentada',
        ),
        migrations.RemoveField(
            model_name='placa_wifi',
            name='realidadAumentada',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='realidadAumentada',
        ),
        migrations.RemoveField(
            model_name='sistema_operativo',
            name='realidadAumentada',
        ),
        migrations.RemoveField(
            model_name='teclado',
            name='realidadAumentada',
        ),
    ]
