# Generated by Django 5.1.5 on 2025-11-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computacion', '0003_remove_cooler_realidadaumentada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gabinete',
            name='realidadAumentada',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='realidadAumentada',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='realidadAumentada',
        ),
        migrations.RemoveField(
            model_name='pcescritorio',
            name='realidadAumentada',
        ),
    ]
