# Generated by Django 5.2.6 on 2025-11-10 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Biografia')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='Avatar')),
                ('experiencia', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('experto', 'Experto')], default='principiante', max_length=50, verbose_name='Nivel de experiencia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='UsuarioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Interes')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interes', to='usuario.perfil', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Interes',
                'verbose_name_plural': 'Intereses',
                'unique_together': {('perfil', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='FavoritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del producto')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de agregado')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de producto')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='usuario.perfil', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Producto Favorito',
                'verbose_name_plural': 'Productos Favoritos',
                'ordering': ['-added_at'],
                'unique_together': {('perfil', 'content_type', 'object_id')},
            },
        ),
    ]
