# Generated by Django 5.1.5 on 2025-11-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='id_proveedor',
            new_name='proveedor',
        ),
    ]
