# Generated by Django 5.2.6 on 2025-11-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='proveedor')),
                ('contacto', models.CharField(max_length=100, verbose_name='contacto')),
                ('telefono', models.CharField(max_length=100, verbose_name='telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('cuit', models.CharField(max_length=150, verbose_name='Cuit')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
        ),
    ]
